local spell_priority = {
    "evade",
    "armored_hide",
    "counterattack",
    "ravager",
    "the_seeker",
    "touch_of_death",
    "concussive_stomp",
    "crushing_hand",
    "payback",
    "quill_volley",
    "rake",
    "razor_wings",
    "rock_splitter",
    "rushing_claw",
    "scourge",
    "soar",
    "stinger",
    "the_devourer",
    "the_hunter",
    "the_protector",
    "thrash",
    "thunderspike",
    "toxic_skin",
    "vortex",
    "withering_fist",
}

return spell_priority
